### ISSUE TITLE
Not work with seneca 2.1.0

### ISSUE THREAD

**Issue by htliu1111** [senecajs/seneca-cassandra-store#5]
Dear Sir,

this version does not work with seneca 2.1.0, nor 3.0.0. 
I followed the instruction in web-site, error thrown as below

name:seneca-mqdtra,plugin:define,role:seneca,seq:6,tag:undefined    96  {role:seneca,plugin:define,name:seneca-mqdtra,tag:null,seq:6}   ENTRY   (r1xr8h234t6o)  GATE    seneca: The plugin seneca-mqdtra uses an unsupported legacy callback to indicate plugin definition is complete: function (seneca, opts, cb) { ... }. The correct format is: function(options) { ... }. For more details, please see http://senecajs.org/tutorials/how-to-write-a-plugin.html    unsupported_legacy_plugin   {options:{name:senecatest,host:127.0.0.1,port:9160},callback:null,history:[],name:seneca-mqdtra,search:[{type:n Error: seneca: The plugin seneca-mqdtra uses an unsupported legacy callback to indicate plugin definition is complete: function (seneca, opts, cb) { ... }. The correct format is: function(options) { ... }. For more details, please see http://senecajs.org/tutorials/how-to-write-a-plugin.html
    at Object.errormaker [as error](D:temp_senecacassandra-testnode_moduleseraroeraro.js:94:15)
    at define_plugin (D:\temp_seneca\cassandra-test\node_modules\seneca\lib\plugins.js:310:21)

**Comment by htliu1111** [comment]
any one have experience using seneca-cassandra-store, please help

**Comment by nawazbaba1993** [comment]
### I am also facing same issue. Please anyone help
